name: Validate Airflow DAG

on:
  push:
    branches:
      - '*'

jobs:
  validate-dag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Use the Python version compatible with your Airflow setup

      - name: Install Airflow and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install apache-airflow

      - name: Validate DAG files
        run: |
          for dag_file in /*.py; do
            echo "Validating $dag_file"
            python -m py_compile $dag_file
            python -c "from airflow.models import DagBag; DagBag().get_dag('$dag_file')"
          done
